import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/Provider/SidebarProvider";
import { UserProvider } from "@/components/Providers/user-provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <UserProvider>
        <SidebarProvider>
          {children}
        </SidebarProvider>
        </UserProvider>
        <Toaster/>
      </body>
    </html>
  );
}
